### ISSUE TITLE
Usage ; running the code

### ISSUE THREAD

**Issue by Ghulam111** [huiqu18/WeaklySegPointAnno#1]
can you please create the template `data`  folder . with the proper directories and `json` file etc. that will be really helpful.

**Comment by huiqu18** [comment]
The organization of data folder:
```
/data
    /MO
        /images
            img1.png
            img2.png
            ...
        /labels_instance
            img1_label.png
            img2_label.png
            ...
```     
The organization in the `train_val_test.json` file:
```
{
"train": [
        "train_img1.png",
        "train_img2.png",
        ...
].
"val": [
        "val_img1.png",
        "val_img2.png",
        ...
],
"test": [
        "test_img1.png",
        "test_img2.png",
        ...
]
}
```
With the images, instance labels and json file, you can run `prepare_data.py` to generate points label, voronoi label and cluster label, as well as all data for training.

You can also run with points label only If no instance labels are available. Just put the label images under the folder `data/{dataset}/labels_point` , and change code in `prepare_data.py` accordingly.
