### ISSUE TITLE
How to generate MoNuSeg's instance label?

### ISSUE THREAD

**Issue by sooperset** [huiqu18/WeaklySegPointAnno#2]
Hi, Thanks for sharing your work!

I'd like to run your code, but i noticed instance_label should be image.
MoNuSeg provides xml file for annotation, so how to convert xml to instance label png?

**Comment by huiqu18** [comment]
You can generate the instance labels using the authors' code: https://nucleisegmentationbenchmark.weebly.com/codes.html

The color normalized images and instance labels are also available at https://github.com/huiqu18/WeaklySegMixedAnno/tree/master/data/MO

**Comment by sooperset** [comment]
@huiqu18 Thanks for a reply.
I cloned the repo below, I noticed several images are different from provided competition data.

> TCGA-21-5784-01Z-00-DX1
> TCGA-A7-A13E-01Z-00-DX1
> TCGA-AY-A8YK-01A-01-TS1
> TCGA-B0-5698-01Z-00-DX1
> TCGA-B0-5710-01Z-00-DX1
> TCGA-B0-5711-01Z-00-DX1
> TCGA-CH-5767-01Z-00-DX1

![image](https://user-images.githubusercontent.com/32061883/75124794-c37d5000-56f4-11ea-844c-944db9b7f580.png)

Competition dataset is updated?

**Comment by huiqu18** [comment]
@Soo95 Yes, they replaced some images with new ones in the dataset around September last year. I don't know the reason.

**Comment by sooperset** [comment]
Thanks a lot!
